### ISSUE TITLE
Backend: GUIslice platform+display regression suite

### ISSUE THREAD

**Issue by ImpulseAdventure** [ImpulseAdventure/GUIslice#65]
Given the number of TFT display modules, graphics libraries and configurations modes supported by GUIslice, it is not practical to use a manual approach to testing new release combinations. An automated regression suite to test the Arduino IDE compilation and Raspberry Pi targets is essential.

Thankfully, I have recently come across the excellent [Arduino-CLI](https://github.com/arduino/arduino-cli) which enables some automation. I will use this issue to capture the current status of this work, but I am always open to suggestions from others who may have experience in this area too.

At this point, a good portion of the supported platforms have already been integrated into the regression suite. I intend to include a selection of sample configuration files for a number of the platforms and TFT modules into the repo later.

### TODO ###
- [x] **Travis-CI** testing of releases / pull requests
*STATUS*: Mostly done, but looking for help to add new targets mentioned in #58
- [x] Regression for **UNO**
*STATUS*: Done
- [x] Regression for **ATmega2560**
*STATUS*: Done
- [x] Regression for **ESP32** & **M5Stack**
*STATUS*: Done. Required fix to arduino-cli (filed https://github.com/arduino/arduino-cli/issues/73)
- [x] Regression for **ESP8266**
*STATUS*: Done. Had same issue as for ESP32
- [x] Regression for **Cortex-M0** (Adafruit Feather M0)
*STATUS*: Done
- [ ] Regression for **Cortex-M4** (nRF52)
*STATUS*: Not started
- [x] Regression for **STM32** using *STM32duino*
*STATUS*: Done
- [x] Regression for **STM32** using *Arduino_STM32*
*STATUS*: Done (manual core install)
- [x] Regression for **LINUX / Raspberry Pi** using *SDL1.2*
*STATUS*: Done
install)
- [ ] Regression for **LINUX / Raspberry Pi** using *SDL2*
*STATUS*: Not started

Note that the above suite is primarily aimed at ensuring compilation is successful locally before pushing to the repository (wherein **travis-ci** will perform a limited sanity check). A matrix of the GUIslice examples and compilation modes are executed in the local regression. Later on, I'd like to devise a suitable way to confirm that runtime operation is as expected too.

The Arduino-CLI will be used for all `\arduino` and `\arduino-min` targets, whereas direct compilation (with SDL in LINUX) will be used for the `\linux` (Raspberry Pi) targets.

For reference, I am running the regressions in a **Xubuntu 16.04** VM using Windows 10.

**Comment by ImpulseAdventure** [comment]
Moved to internal future enhancement
